server.port=8081
server.servlet.context-path=/

# SpringDoc OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Logging
logging.level.org.springframework.ws=DEBUG
logging.level.com.ecommerce.inventario=INFO
